# Generated by Django 6.1.1 on 2026-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
